// Copyright (C) 2026 - ZKNOX
// License: This software is licensed under MIT License
// FILE: js/gen_test_vectors65.js
// Description: writes the ML-DSA-65 test vectors of the Solidity test suite
// from the NIST files in test/KAT/ (run from the repository root:
// `node js/gen_test_vectors65.js [rspCounts]`, default 10):
//   - test/dilithium65KATS.t.sol: count 0 of PQCsignKAT_Dilithium3.rsp as a
//     literal test, the same form as test/dilithiumKATS.t.sol (ML-DSA-44);
//   - test/KAT/mldsa65_vectors.json: the NIST ACVP ML-DSA-65 sigVer vectors
//     (external interface, pure, contexts of 0..255 bytes, valid and
//     corrupted signatures) and the first `rspCounts` vectors of the .rsp,
//     each with the on-chain public key blob, read by
//     test/dilithium65_vectors.t.sol.
import fs from 'fs';
import { expandPublicKey65, encodePublicKeyBlob65, hexToBytes, bytesToHex, keygen, sign, verify, PARAMS } from './mldsa65.js';
import { keccak_256 } from '@noble/hashes/sha3.js';
import { parseRsp } from './kat_rsp.js';

const KAT = 'test/KAT';
const rspCounts = process.argv[2] ? parseInt(process.argv[2], 10) : 10;

const rsp = parseRsp(fs.readFileSync(`${KAT}/PQCsignKAT_Dilithium3.rsp`, 'utf8'));

// ---------------------------------------------------------------- literal test
function literalTest(v) {
  const { aHat, t1Hat, tr } = expandPublicKey65(v.pk);
  const sig = v.sm.slice(0, PARAMS.SIG_BYTES);
  const hex = (b) => Buffer.from(b).toString('hex');
  const word = (w) => '0x' + w.toString(16).padStart(64, '0');
  let s = '';
  s += '// SPDX-License-Identifier: UNLICENSED\n';
  s += 'pragma solidity ^0.8.13;\n';
  s += '// GENERATED by js/gen_test_vectors65.js -- do not edit by hand.\n';
  s += `// NIST reference implementation KAT (pq-crystals/dilithium, FIPS 204 ML-DSA-65),\n`;
  s += `// test/KAT/PQCsignKAT_Dilithium3.rsp, count = ${v.count}: pk expanded to the on-chain\n`;
  s += `// form (A_hat = ExpandA(rho), t1 = NTT(t1 * 2^13), tr = SHAKE256(pk, 64)) by js/mldsa65.js.\n\n`;
  s += 'import {Test, console} from "forge-std/Test.sol";\n';
  s += 'import {ZKNOX_dilithium65} from "../src/ZKNOX_dilithium65.sol";\n';
  s += 'import {F1600Helper} from "./F1600Helper.sol";\n';
  s += 'import {SSTORE2} from "sstore2/SSTORE2.sol";\n\n';
  s += 'contract KATDilithium65Test is Test {\n';
  s += '    ZKNOX_dilithium65 dilithium;\n\n';
  s += '    function setUp() public {\n';
  s += '        dilithium = new ZKNOX_dilithium65(F1600Helper.deploy(vm));\n';
  s += '    }\n\n';
  s += '    function _pubKey() internal returns (bytes memory pk) {\n';
  s += '        // Public key\n';
  s += `        // pubkey = ${hex(v.pk)}\n`;
  s += `        uint256[][][] memory aHat = new uint256[][][](${PARAMS.K});\n`;
  s += `        for (uint256 i = 0; i < ${PARAMS.K}; i++) {\n`;
  s += `            aHat[i] = new uint256[][](${PARAMS.L});\n`;
  s += `            for (uint256 j = 0; j < ${PARAMS.L}; j++) {\n`;
  s += '                aHat[i][j] = new uint256[](32);\n';
  s += '            }\n';
  s += '        }\n';
  for (let i = 0; i < PARAMS.K; i++) {
    for (let j = 0; j < PARAMS.L; j++) {
      for (let m = 0; m < 32; m++) {
        s += `        aHat[${i}][${j}][${m}] = uint256(${word(aHat[i][j][m])});\n`;
      }
    }
  }
  s += `        bytes memory tr =\n            hex"${hex(tr)}";\n`;
  s += `        uint256[][] memory t1 = new uint256[][](${PARAMS.K});\n`;
  s += `        for (uint256 i = 0; i < ${PARAMS.K}; i++) {\n`;
  s += '            t1[i] = new uint256[](32);\n';
  s += '        }\n';
  for (let i = 0; i < PARAMS.K; i++) {
    for (let m = 0; m < 32; m++) {
      s += `        t1[${i}][${m}] = uint256(${word(t1Hat[i][m])});\n`;
    }
  }
  s += '\n        // two SSTORE2 halves (rows 0..2 / 3..5 of A, t1[0..2] / t1[3..5], tr in both)\n';
  s += '        pk = new bytes(40);\n';
  s += '        for (uint256 h = 0; h < 2; h++) {\n';
  s += '            uint256[][][] memory rows = new uint256[][][](3);\n';
  s += '            uint256[][] memory t1Half = new uint256[][](3);\n';
  s += '            for (uint256 i = 0; i < 3; i++) {\n';
  s += '                rows[i] = aHat[3 * h + i];\n';
  s += '                t1Half[i] = t1[3 * h + i];\n';
  s += '            }\n';
  s += '            address pointer = SSTORE2.write(abi.encode(abi.encode(rows), tr, abi.encode(t1Half)));\n';
  s += '            assembly {\n';
  s += '                mstore(add(add(pk, 32), mul(h, 20)), shl(96, pointer))\n';
  s += '            }\n';
  s += '        }\n';
  s += '    }\n\n';
  s += '    function _signature() internal pure returns (bytes memory) {\n';
  s += `        // sm = signature (${PARAMS.SIG_BYTES} bytes) || message\n`;
  s += `        return hex"${hex(sig)}";\n`;
  s += '    }\n\n';
  s += '    function _message() internal pure returns (bytes memory) {\n';
  s += `        // mlen = ${v.mlen}\n`;
  s += `        return hex"${hex(v.msg)}";\n`;
  s += '    }\n\n';
  s += '    function testVerify() public {\n';
  s += '        bytes memory pk = _pubKey();\n';
  s += '        bytes memory sig = _signature();\n';
  s += '        bytes memory msgs = _message();\n\n';
  s += '        uint256 gasStart = gasleft();\n';
  s += '        bool ver = dilithium.verify(pk, msgs, sig, "");\n';
  s += '        uint256 gasUsed = gasStart - gasleft();\n';
  s += '        console.log("Gas used:", gasUsed);\n';
  s += '        assertTrue(ver);\n';
  s += '    }\n\n';
  s += '    /// one corrupted byte in each of the three fields of the signature, and a\n';
  s += '    /// corrupted message: all rejected\n';
  s += '    function testRejects() public {\n';
  s += '        bytes memory pk = _pubKey();\n';
  s += '        bytes memory msgs = _message();\n';
  s += '        uint256[3] memory positions = [uint256(5), 1000, 3300]; // c~, z, h\n';
  s += '        for (uint256 i = 0; i < 3; i++) {\n';
  s += '            bytes memory sig = _signature();\n';
  s += '            sig[positions[i]] ^= 0x01;\n';
  s += '            assertFalse(dilithium.verify(pk, msgs, sig, ""));\n';
  s += '        }\n';
  s += '        bytes memory badMsg = _message();\n';
  s += '        badMsg[0] ^= 0x01;\n';
  s += '        assertFalse(dilithium.verify(pk, badMsg, _signature(), ""));\n';
  s += '        // a context changes M\': the signature was made with an empty context\n';
  s += '        assertFalse(dilithium.verify(pk, msgs, _signature(), hex"00"));\n';
  s += '    }\n';
  s += '}\n';
  return s;
}

fs.writeFileSync('test/dilithium65KATS.t.sol', literalTest(rsp[0]));
console.log('wrote test/dilithium65KATS.t.sol (rsp count 0)');

// ---------------------------------------------------------------- JSON vectors
const vectors = [];
const sigVer = JSON.parse(fs.readFileSync(`${KAT}/ACVP_ML-DSA-65_sigVer-FIPS204.json`, 'utf8'));
for (const g of sigVer.testGroups) {
  if (g.signatureInterface !== 'external' || g.preHash !== 'pure') continue;
  for (const t of g.tests) {
    const pk = hexToBytes(t.pk);
    vectors.push({
      name: `ACVP ML-DSA-65 sigVer tgId ${g.tgId} tcId ${t.tcId}: ${t.reason}`,
      source: 'usnistgov/ACVP-Server gen-val/json-files/ML-DSA-sigVer-FIPS204/internalProjection.json',
      tcId: t.tcId,
      pk: bytesToHex(pk),
      blob: encodePublicKeyBlob65(expandPublicKey65(pk)).setKeyData,
      msg: '0x' + t.message.toLowerCase(),
      ctx: '0x' + t.context.toLowerCase(),
      sig: '0x' + t.signature.toLowerCase(),
      valid: t.testPassed,
    });
  }
}
console.log(`ACVP sigVer (external, pure): ${vectors.length} vectors`);
for (const v of rsp.slice(0, rspCounts)) {
  vectors.push({
    name: `PQCsignKAT_Dilithium3.rsp count ${v.count}`,
    source: 'pq-crystals/dilithium ref/nistkat/PQCgenKAT_sign (FIPS 204 ML-DSA-65)',
    tcId: v.count,
    pk: bytesToHex(v.pk),
    blob: encodePublicKeyBlob65(expandPublicKey65(v.pk)).setKeyData,
    msg: bytesToHex(v.msg),
    ctx: '0x',
    sig: bytesToHex(v.sm.slice(0, PARAMS.SIG_BYTES)),
    valid: true,
  });
}
// the JS signer itself: a key from a fixed seed, a message with a context,
// deterministic and hedged signatures (the hedged one with a fixed rnd)
{
  const { publicKey, secretKey } = keygen(hexToBytes('0x' + 'deadbeef'.repeat(8)));
  const msg = new TextEncoder().encode('ETHDILITHIUM ML-DSA-65 js signer test message');
  const ctx = hexToBytes('0x5a4b4e4f58'); // "ZKNOX"
  const blob = encodePublicKeyBlob65(expandPublicKey65(publicKey)).setKeyData;
  const det = sign(msg, secretKey, { context: ctx });
  const hedged = sign(msg, secretKey, { context: ctx, rnd: hexToBytes('0x' + '01'.repeat(32)) });
  if (!verify(det, msg, publicKey, ctx) || !verify(hedged, msg, publicKey, ctx)) throw new Error('js signer self-check failed');
  for (const [label, sig] of [['deterministic', det], ['hedged (rnd = 0x01..01)', hedged]]) {
    vectors.push({
      name: `js/mldsa65.js keygen(seed 0xdeadbeef..) + sign(msg, ctx "ZKNOX"), ${label}`,
      source: 'js/mldsa65.js (@noble/post-quantum ml_dsa65)',
      tcId: 1000 + vectors.length,
      pk: bytesToHex(publicKey),
      blob,
      msg: bytesToHex(msg),
      ctx: bytesToHex(ctx),
      sig: bytesToHex(sig),
      valid: true,
    });
  }
  // the same signature with another context, and a truncated context: rejected
  vectors.push({
    name: 'js/mldsa65.js deterministic signature with the wrong context',
    source: 'js/mldsa65.js (@noble/post-quantum ml_dsa65)',
    tcId: 1000 + vectors.length,
    pk: bytesToHex(publicKey),
    blob,
    msg: bytesToHex(msg),
    ctx: '0x5a4b4e4f',
    sig: bytesToHex(det),
    valid: false,
  });
}
// the ISigVerifier interface verify(pk, bytes32 hash, sig) checks the pure
// ML-DSA-65 signature of the 32-byte hash with an empty context: one made here
// with the secret key of .rsp count 0
const hash = keccak_256(new TextEncoder().encode('ZKNOX ML-DSA-65 hash32 test vector'));
const hashSig = sign(hash, rsp[0].sk, { deterministic: true });
if (!verify(hashSig, hash, rsp[0].pk)) throw new Error('hash32 signature does not verify');
const hash32 = { key: 'PQCsignKAT_Dilithium3.rsp count 0', hash: bytesToHex(hash), sig: bytesToHex(hashSig) };
fs.writeFileSync(`${KAT}/mldsa65_vectors.json`, JSON.stringify({ count: vectors.length, hash32, vectors }, null, 1));
// count 0 alone, with its expanded key, for the kernel tests (small file, fast to parse)
{
  const v = rsp[0];
  const { aHat, t1Hat, tr } = expandPublicKey65(v.pk);
  const { halves, setKeyData } = encodePublicKeyBlob65({ aHat, t1Hat, tr });
  const kat0 = {
    source: 'PQCsignKAT_Dilithium3.rsp count 0',
    pk: bytesToHex(v.pk),
    blob: setKeyData,
    half0: halves[0],
    half1: halves[1],
    tr: bytesToHex(tr),
    msg: bytesToHex(v.msg),
    sig: bytesToHex(v.sm.slice(0, PARAMS.SIG_BYTES)),
  };
  fs.writeFileSync(`${KAT}/mldsa65_kat0.json`, JSON.stringify(kat0, null, 1));
  console.log(`wrote ${KAT}/mldsa65_kat0.json`);
}
console.log(`wrote ${KAT}/mldsa65_vectors.json: ${vectors.length} vectors (${rspCounts} from the .rsp)`);
